inventory:
  plugin: SimpleInventory #we're using SimpleInventory here, other options are Ansible, Netbox and NSOT
  options:
    host_file: "../inventory/core.yaml"
    group_file: "../inventory/groups.yaml"
    defaults_file: "../inventory/defaults.yaml"
runners:
  plugin: threaded #this makes Nornir threaded, the default is non-threaded
  options:
    num_workers: 10 #default is 20